<a href="https://colab.research.google.com/github/rlfwo93/machine-learning/blob/master/indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #넘파이  모듈

# 2차원 행렬 인덱싱

In [2]:
a = np.array([10,20,30,40,50,60]).reshape(3,2)
print("a = {0}".format(a), end = "\n\n")
print("a[0:-1, 1:2] ==", a[0:-1, 1:2])  # == A[0:2, 1:2]
print("a[-1:-2, 1:2] ==", a[0:-1, 1:2], end = "\n\n--------------------------------\n\n")

# 앞부분은 행을 뒷 부분은 열을 나타냄 

a = [[10 20]
 [30 40]
 [50 60]]

a[0:-1, 1:2] == [[20]
 [40]]
a[-1:-2, 1:2] == [[20]
 [40]]

--------------------------------



In [13]:
c = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160]).reshape(4,4)
print("c = {0}".format(c), end = "\n\n")
print("c[0:-1, 1:2] ==", c[0:-1, 1:4])  
print("c[-1:-2, 1:2] ==", c[0:-1, 1:2], end = "\n\n--------------------------------\n\n")


# 앞부분은 행을 뒷 부분은 열을 나타냄

c = [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

c[0:-1, 1:2] == [[ 20  30  40]
 [ 60  70  80]
 [100 110 120]]
c[-1:-2, 1:2] == [[ 20]
 [ 60]
 [100]]

--------------------------------

