<a href="https://colab.research.google.com/github/rlfwo93/machine-learning/blob/master/numpy_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

numpy의 개념과 numpy가 필요한 이유, numpy를 이용하여 벡터와 matrix 즉, 행렬을 만들고 이를 상호변환 시킬 수 있는 API를 사용하는 방법에 대해 알아본다.

numpy의 개념, 그리고 numpy를 사용하는 이유¶
numpy

numpy는 머신러닝 코드 개발을 할 경우 자주 사용되는 벡터, 행렬 등을 표현하고 연산할 때 반드시 필요한 라이브러리다.
벡터와 행렬을 이용하면 수치계산이 매우 빨리 수행된다.
numpy array vs. list

머신러닝에서 숫자, 사람, 동물 등의 인식을 하기 위해서는 이미지 데이터를 행렬(matrix)로 변환하는 것이 중요하다.
## 행렬을 나타내기 위해서는 list를 사용할 수도 있지만, 행렬 연산이 직관적이지 않고 오류 가능성이 높기 때문에 행렬 연산을 위해서는 numpy 사용이 필수적이다. 




# import로 모듈을 불러오고 as로 모듈의 이름을 지정

In [ ]:
import numpy as np
 

# 모듈 지정하기 사용




In [ ]:
a = np.array(range(1,5)).reshape(2,2)
# np모듈을 사용하여 1~5까지 숫자를 reshape를 이용하여 2행2열로 만든다는 것 
print(a)

[[1 2]
 [3 4]]


In [ ]:
a.shape # 배열a의 형식을 보여줌

(2, 2)

In [ ]:
ar2 = np.array(range(1,7)).reshape(2,3)
ar2
# 1~6까지의 숫자를 2행 3열로 만든다는것 

array([[1, 2, 3],
       [4, 5, 6]])

# numpy vector(1차원 배열)
  < array 생성방법>

1.벡터는 np.array([...])를 사용하여 생성한다.

2.np.array(range()).reshape

3.np.array().reshape


머신러닝 코드 구현 시, 연산을 위해서 벡터, matrix 등의 구조(shape), 차원(dimension)을 확인하는 것이 필요하다.

In [ ]:
a = np.array([1,2,3])
b = np.array(range(1,5))
c = np.array(range(1,5)).reshape(2,2)
d = np.array([1,2,3,4]).reshape(2,2)
#reshape = 행과열을 설정하여 만듬
#배열을 생성하는 다양한 방법이 있음.


print("a = ",a)
print("\n")
print("b = ",b)
print("\n")
print("c = ",c)
print("\n")
print("d = ",d)

a =  [1 2 3]


b =  [1 2 3 4]


c =  [[1 2]
 [3 4]]


d =  [[1 2]
 [3 4]]


# 구조와 차원 확인해보기


In [ ]:
a = np.array([1,2,3])
b = np.array(range(1,5)).reshape(4,1)
print("a = ",a)
print("a.shape = ",a.shape) #shpae함수는 구조를 확인하는 함수
print("a.ndim = ",a.ndim, end = "\n\n--------------------------------\n\n") # ndim함수는 차원을 확인하는 함수

print("b = ",b)
print("b.shape = ",b.shape) # (2,2)행렬이기 떄문에 2,2가 나옴
print("b.ndim = ",b.ndim) #2차원이기떄문에 2가 나옴 


a =  [1 2 3]
a.shape =  (3,)
a.ndim =  1

--------------------------------

b =  [[1]
 [2]
 [3]
 [4]]
b.shape =  (4, 1)
b.ndim =  2


# 행벡터와 열벡터

행벡터란 크기가 인 행렬, 즉 한 행만 있는 행렬을 말하고 다음과 같이 나타낸다.

b =  [1 2 3 4]


열벡터란 크기가 인 행렬, 즉 한 열만 있는 행렬을 말하며 열행렬이라고도 한다.

c =
  [[1]
 
  [2]
 
  [3]
 
 [4]]

# 열백터로 변환

In [ ]:
a = np.array([1,2,3,4])
a1=a[:, np.newaxis] #열부분에 newaxis를 사용하면 한차원을 분해하고 추가함
a2=a.reshape(4,1) #reshape를 이용하여 행변형을 할 수 있다
print("a = ",a)
print("a1 = ",a1)
print("a2 = ",a2)


a =  [1 2 3 4]
a1 =  [[1]
 [2]
 [3]
 [4]]
a2 =  [[1]
 [2]
 [3]
 [4]]


# 행백터로 변환

In [ ]:
a = np.array([1,2,3,4])
a1 = a[np.newaxis,:]
print("a1 = ",a1)



a1 =  [[1 2 3 4]]


# 리스트와 행렬 차이

In [ ]:
a = [1,2]
b = [3,4]
a+b 

#리스트는 연산을 하는것이 아니라 a,b의 리스트를 합쳐줌

[1, 2, 3, 4]

In [ ]:
a= np.array([1,2])
b= np.array([3,4])
a+b
#행렬은 a,b에 있는 값들을 연산시켜줌

array([4, 6])

# 백터 산술연산

벡터 간 산술연산 (+, -, x, /, %)는 벡터의 각각의 원소에 대해서 행해진다.

In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])

A1= np.array([[1,2,3,4]])
B1= np.array([1])

A2= np.array([1,2,3,4])
B2= 2

print("A+B = ", A+B)
print("A-B = ", A-B)
print("A*B = ", A*B)
print("A/B = ", A/B)
print("A%B = ", A%B, end = "\n\n--------------------------------\n\n")

print("A1+B1 = ", A1+B1)
print("A1-B1 = ", A1-B1)
print("A1*B1 = ", A1*B1)
print("A1/B1 = ", A1/B1)
print("A1%B1 = ", A1%B1, end = "\n\n--------------------------------\n\n")

print("A2+B2 = ", A2+B2)
print("A2-B2 = ", A2-B2)
print("A2*B2 = ", A2*B2)
print("A2/B2 = ", A2/B2)
print("A2%B2 = ", A2%B2)

A+B =  [5 7 9]
A-B =  [-3 -3 -3]
A*B =  [ 4 10 18]
A/B =  [0.25 0.4  0.5 ]
A%B =  [1 2 3]

--------------------------------

A1+B1 =  [[2 3 4 5]]
A1-B1 =  [[0 1 2 3]]
A1*B1 =  [[1 2 3 4]]
A1/B1 =  [[1. 2. 3. 4.]]
A1%B1 =  [[0 0 0 0]]

--------------------------------

A2+B2 =  [3 4 5 6]
A2-B2 =  [-1  0  1  2]
A2*B2 =  [2 4 6 8]
A2/B2 =  [0.5 1.  1.5 2. ]
A2%B2 =  [1 0 1 0]


# numpy matrix (2차원 행렬)


행렬 생성
행렬 생성
matrix는 벡터와 마찬가지로 np.array([ [...], [...], ... ])를 사용하여 생성한다.

예)  

import numpy as np

      A = (1 2 3)       B = (-1 -2 -3)
          (4 5 6)           (-4 -5 -6)
        shape 2x3       shape 2x3

In [ ]:

A = np.array([ [1,2,3], [4,5,6] ])
B = np.array([ [-1,-2,-3], [-4,-5,-6] ])

# vector A, B 구조 출력 => shape
print("A.shape = {0}, B.shape =  {1}".format(A.shape, B.shape))

# vector A, B 차원 출력 => ndim
print("A.ndim = {0}, B.ndim = {1}".format(A.ndim, B.ndim))

A.shape = (2, 3), B.shape =  (2, 3)
A.ndim = 2, B.ndim = 2


# 2차원 행렬 형 변환

In [ ]:

# reshape()를 이용한 열벡터 생성

C = np.array([1,2,3])  # 기본 벡터
print("C = ",C)
# 벡터 C의 구조 출력 => shape
print("C.shape = ", C.shape, end = "\n\n--------------------------------\n\n")

# 벡터를 (3,1) 행렬로 형 변환 => 열벡터로 변환
C1 = C.reshape(3,1)
print("C1 = ", C1)
print("C1.shape = ", C1.shape, end = "\n\n--------------------------------\n\n")

C2 = C.reshape(1,3) # 벡터를 (1,3) 행렬로 형 변환 => 행벡터로 변환
print("C2 = ", C2)
print("C2.shape = ", C2.shape)

C =  [1 2 3]
C.shape =  (3,)

--------------------------------

C1 =  [[1]
 [2]
 [3]]
C1.shape =  (3, 1)

--------------------------------

C2 =  [[1 2 3]]
C2.shape =  (1, 3)


In [ ]:
D = np.array([ [1,2,3], [4,5,6] ])  # (2,3) 행렬
#각 행렬에 있는 원소의 갯수가 같아야함. 

# 배열 D의 구조 출력 => shape
print("D.shape = ", D.shape, end = "\n\n")

# 배열 D를 (3,2) 행렬로 형 변환 
D1 = D.reshape(3,2)

print("D1.shape = ", D1.shape, end = "\n\n")

# D와 D1 출력
print(D, end = "\n\n")
print(D1)

D.shape =  (2, 3)

D1.shape =  (3, 2)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


# numpy 행렬 곱 (dot product)

A 행렬과 B 행렬의 행렬 곱 (dot product)는 np.dot(A,B)로 나타내며, 행렬 A의 열벡터와 B 행렬의 행벡터가 같아야 한다.

만약 같지 않으면 reshape 또는 전치행렬(transpose) 등을 사용하여 형 변환을 한 후에 행렬 곱을 실행해야 한다.



행렬 곱은 사칙연산과는 다른 특징을 가진다.

행렬 곱은 행렬의 원소 개수가 같아야만 계산할 수 있는 사칙연산의 한계를 벗어나
행렬 곱 조건을 만족하는 다양한 크기의 행렬을 연속으로 만들고
행렬 곱을 연속으로 계산하면서
결괏값을 만들 수 있기 때문에 머신러닝과 이미지 프로세싱 분야에서 자주 사용된다.
    예) 입력 행렬 형상이 64X64이고, 결과 행렬 형상이 64X10이라면, 중간에 dot product 를 만족시키는 어떤 형상의 행렬이라도 가질 수 있다.

행렬 곱을 사용하지 않고 산술 연산만 가능하다면, 입력 행렬의 64X64 크기를 가지는 특성 값만을 사용해야 하기 때문에 다양한 특성을 갖는 필터 개발이 불가능하다.

In [ ]:
a = np.array([ [1,2,3], [4,5,6] ]) # 2x3 행렬
b = np.array([ [-1,-2], [-3,-4], [-5,-6] ]) # 3x2 행렬
c = np.dot(a,b)
print("c = ",c, end = "\n\n--------------------------------\n\n")


a1 = np.array( [[1,2,3], [4,5,6],[7,8,9]])
b2 = np.array([[1,2], [4,5],[7,8]])
c2 = np.dot(a1,b2)
print("c2 = ",c2, end = "\n\n--------------------------------\n\n")


a3 = np.array([ [1,2], [3,4] ]) 
b3 = np.array([ [1,2,3], [4,5,6,] ])
c3 = np.dot(a3,b3)
print("c3 = ",c3, end = "\n\n--------------------------------\n\n")


a4 = np.array([[[1,2,3]]])
a5 = np.array([1,2,3])
c4 = np.dot(a4,a5)
print("c4 = ",c4)

c =  [[-22 -28]
 [-49 -64]]

--------------------------------

c2 =  [[ 30  36]
 [ 66  81]
 [102 126]]

--------------------------------

c3 =  [[ 9 12 15]
 [19 26 33]]

--------------------------------

c4 =  [[14]]


# concatenate 함수사용 
concatenate 함수는 배열을 합쳐준다.

axis는 기준이다

axis = 0: Y축 (세로 방향) 으로 설정합니다.

axis = 1: X축 (가로 방향) 으로 설정합니다.


In [ ]:
a1=np.concatenate((a,ar2),axis=1)

a1

#가로방향으로 합치려면 행의 갯수가 같아야함

array([[1, 2, 1, 2, 3],
       [3, 4, 4, 5, 6]])

In [ ]:
a2=np.concatenate((a,ar2),axis=0)

a2

#세로방향으로 합치려면 열의 갯수가 같아야함.

ValueError: ignored

In [ ]:
np.concatenate((a,a),axis=0) 
#axis=0은 세로

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [ ]:
np.concatenate((a,a),axis=1)
#axis=1은 가로

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

# BroadCasting

 일정조건을 부합하는 다른 형태의 배열끼리 연산을 수행하는 것.

1.맴버가 하나인 배열은 어떤 배열이나 브로드캐스팅이가능

2.하나의 배열의 차원이 1인 경우 브로드캐스팅가능

3.차원의 짝이 맞을 떄 브로드캐스팅가능





In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a+b

array([3., 4., 5.])

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a+b

array([3., 4., 5.])

In [ ]:
 a= np.array([[1],
             [2],
             [3],
             [4]])
 b=2
 a+b


array([[3],
       [4],
       [5],
       [6]])

In [ ]:
 a= np.array([[1],
             [2],
             [3],
             [4]])
 
 b = [1,2,3,4]

 a+b

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [ ]:
a= np.array([[1],
             [2],
             [3],
             [4]])
 
b= np.array([[1],
             [2],
             [3],
             [4]])

a+b

array([[2],
       [4],
       [6],
       [8]])

# 2차원 브로드캐스팅

In [ ]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])

a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [ ]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b=[[1]]
a+b

array([[ 1.,  1.,  1.],
       [11., 11., 11.],
       [21., 21., 21.],
       [31., 31., 31.]])

# newaxis사용
newaxis = 행렬로 차원 확장에 사용됨

행 부분에 np.newaxis를 입력시, 차원을 한 단계 추가합니다.

열 부분에 np.newaxis를 입력시, 차원을 분해한 후 한 단계 추가합니다.


In [ ]:
a = np.array([1,2,3,4])
arr = a[np.newaxis,:]
#행부분에 np.newaxis 차원을 한 단계 추가

arr

array([[1, 2, 3, 4]])

In [ ]:
a = np.array([1,2,3,4])
arr = a[:,np.newaxis]
#열부분에 np.newaxis 차원을 분해한 후  한 단계 추가

arr

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
a = np.array([1,2,3,4])
arr = a[:,np.newaxis]

#[[1],
#[2],
#[3],
#[4]])

b = 3

arr+b

array([[4],
       [5],
       [6],
       [7]])

# numpy 전치행렬(transpose)


어떤 행렬의 전치행렬은 원본 행렬의 열은 행으로, 행은 열로 바꾼 것이다.

원본 행렬을 A라고 하면 전치행렬은 A.T 로 나타낸다.

즉, 1행은 1열로 바꾸고 2행은 2열로, 3행은 3열로 바꾼 행렬을 의미한다.

# 전치행렬은 2차원이상 부터 사용가능하다



In [ ]:
a = np.array([ [1,2],[3,4],[5,6] ]) # 3x2행렬
b = a.T  # A의 전치행렬, 2x3행렬

print("a.shape ==", a.shape, ", b.shape ==", b.shape, end = "\n\n")
print("a = {0}".format(a), end = "\n\n")
print("b = {0}".format(b), end = "\n\n--------------------------------\n\n")


 
c = np.array([[1,2],
              [3,4],
              [5,6]])

f= np.array([[1,2],[3,4],[5,6]])
#입력한 형식은 다르나 출력되는 형식은 같음 


d=c.T
print("c = {0}".format(c), end = "\n\n")
print("f = {0}".format(f), end = "\n\n")
print("c.shape = ",c.shape, end = "\n\n")
print("f.shape = ",f.shape, end = "\n\n")
print("d = {0}".format(d), end = "\n\n")

a.shape == (3, 2) , b.shape == (2, 3)

a = [[1 2]
 [3 4]
 [5 6]]

b = [[1 3 5]
 [2 4 6]]

--------------------------------

c = [[1 2]
 [3 4]
 [5 6]]

f = [[1 2]
 [3 4]
 [5 6]]

c.shape =  (3, 2)

f.shape =  (3, 2)

d = [[1 3 5]
 [2 4 6]]



In [ ]:
# vector 전치행렬

C = np.array([1,2,3,4,5]) # vector, matrix 아님 1차원임
D = C.T  # C는 벡터이므로 transpose 안됨

E = C.reshape(1,5) # 1x5 matrix #reshpae를 이용하여 2차원행렬로 만들어줌
F = E.T  # E의 전치행렬 # E는 2차원이기때문에 transpose 함수 사용가능.

print("C = {0}".format(C), end = "\n\n")
print("D = {0}".format(D), end = "\n\n")
print("E = {0}".format(E), end = "\n\n")
print("F = {0}".format(F), end = "\n\n")

C = [1 2 3 4 5]

D = [1 2 3 4 5]

E = [[1 2 3 4 5]]

F = [[1]
 [2]
 [3]
 [4]
 [5]]



#numpy 행렬 원소 접근 


행렬 원소를 명시적(explicit)으로 접근하기 위해서는 리스트에서처럼, 인덱싱 & 슬라이싱 모두 사용이 가능하다.

In [ ]:
a = np.array([10,20,30,40,50,60]).reshape(3,2)
print("a = {0}".format(a), end = "\n\n")

print("a[0,0] = {0}".format(a[0,0]))
print("a[1,0] = {0}".format(a[1,0]))
print("a[2,1] = {0}".format(a[2,1]), end = "\n\n--------------------------------\n\n")

b = np.array([10,20,30,40,50])
print("b[0] = {0}".format(b[0]))
print("b[0,0] = {0}".format(b[0,0])) # 1차원이기때문에 행렬 원소0이라는 개념이 없음 그렇기 때문에 에러발생

a = [[10 20]
 [30 40]
 [50 60]]

a[0,0] = 10
a[1,0] = 30
a[2,1] = 60

--------------------------------

b[0] = 10


IndexError: ignored

In [ ]:
# 예제3 - 슬라이싱
a = np.array([10,20,30,40,50,60]).reshape(3,2)
print("a = {0}".format(a), end = "\n\n")
print("a[0:-1, 1:2] ==", a[0:-1, 1:2])  # == A[0:2, 1:2]
print("a[-1:-2, 1:2] ==", a[0:-1, 1:2], end = "\n\n--------------------------------\n\n")

b = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("b = {0}".format(b), end = "\n\n")
print("b[0:-1, 1:2] ==", b[0:-1, 1:2], end = "\n\n--------------------------------\n\n")  


c = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160]).reshape(4,4)
print("c = {0}".format(c), end = "\n\n")
print("c[0:-1, 1:2] ==", c[0:2, 1:2])  # == A[0:2, 1:2]
print("c[-1:-2, 1:2] ==", c[0:-1, 1:2], end = "\n\n--------------------------------\n\n")

a = [[10 20]
 [30 40]
 [50 60]]

a[0:-1, 1:2] == [[20]
 [40]]
a[-1:-2, 1:2] == [[20]
 [40]]

--------------------------------

b = [[10 20 30]
 [40 50 60]
 [70 80 90]]

b[0:-1, 1:2] == [[20]
 [50]]

--------------------------------

c = [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

c[0:-1, 1:2] == [[20]
 [60]]
c[-1:-2, 1:2] == [[ 20]
 [ 60]
 [100]]

--------------------------------



In [ ]:
)